MPESA_CONSUMER_KEY: 'AMB3MGDTh1iuqm64ZWShxWy37xpArmH6'
MPESA_CONSUMER_SECRET: 'qeQybTNUA5uach9h'
MPESA_PASSKEY: 'bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919'
MPESA_SHORTCODE: '174379'
MPESA_INITIATOR_NAME: 'testapi'
MPESA_INITIATOR_PASSWORD: 'Safaricom999!*!'
CALLBACK_URL: 'https://5457-102-219-208-174.ngrok-free.app'
REGISTER_URL: "https://sandbox.safaricom.co.ke/mpesa/c2b/v1/registerurl"