puts "🌱 Seeding Events..."

Event.create([{
    title: "Gentleman Live in Nairobi",
             image: "https://tikiti.co.ke/images/6421b308c1e2d.jpg",
             category: "Music",
             description: "Experience the real deal with Gentleman and The Evolution Band! Rooted in Reggae, Gentleman's focus on uplifting lyrics and high production has established him as an authentic German Reggae artist. He's won multiple national and international awards, and even has a current hit in the Turkish charts.",
             hosted_by: "Gentlemen",
             featuring: "Gentle bands",
             dress_code: "Casual",
             location: "Nairobi",
             date: Date.new(2023, 6, 15),
             time: Time.new(2023, 6, 15, 19, 0, 0),
             tickets: 10,
             price: 10
           
},
{
    title: "Betrayal in the city",
        image: "https://tikiti.co.ke/images/63ce9626c8a69.jpg",
        category: "Theatre plays",
        description: "Betrayal in the City is a powerful play written by Kenyan playwright Francis Imbuga. It tells the story of Jusper, a university graduate who returns home to his African country after studying abroad. Jusper's homecoming is marked by tragedy when his father, a former government minister, is killed by the government for speaking out against corruption and oppression.",
        hosted_by: "Francis Imbuga",
        featuring: "Various actors",
        dress_code: "Smart casual",
        location: "Kenya National Theatre",
        date: Date.new(2023, 7, 1),
        time: Time.new(2023, 7, 1, 18, 0, 0),
        tickets: 200,
        price: 20
},
{
  title: "Friday Fight Night",
             image: "https://tikiti.co.ke/images/633fe1ded4edb.jpg",
             category: "Sports",
             description: "As the fight progresses, the intensity increases, and the stakes become higher. In the final rounds, the fighters may be exhausted and battered, but they continue to battle on, fueled by their determination to win. The decision of the judges or a knockout will ultimately determine the winner, and the victor is usually celebrated with a shower of applause and confetti.",
             hosted_by: "King Rock",
             featuring: "Local Boxers",
             dress_code: "Casual",
             location: "Carnivore Grounds",
             date: Date.new(2023, 8, 15),
             time: Time.new(2023, 8, 15, 12, 0, 0),
             tickets: 300,
             price: 20
             
},
{
   title: "Cultural Festival",
             image: "https://tikiti.co.ke/images/6261d30b0af05.jpg",
             category: "Culture",
             description: "Get Ready to Celebrate our Culture through Music and Dance 
                           the 10th of December 2022 at the Winning Post, Ngong Race Course.",
             hosted_by: "Mejja Genge",
             featuring: "Local talent",
             dress_code: "Casual",
             location: "City Center",
             date: Date.new(2023, 8, 15),
             time: Time.new(2023, 8, 15, 12, 0, 0),
             tickets: 400,
             price: 20
          
},
{
   title: "concours D'elegance",
             image: "https://tikiti.co.ke/images/62ebba36dd39c.jpg",
             category: "Motor Show",
             description: ".",
             hosted_by: "The 2022 edition of the Golden Africa Concour's d'Elegance will be a celebration of the 50th annual Concours organized by the Alfa Romeo Owners Club (Kenya). 
                        The event is open to all makes of cars and motorcycles and is the classiest event on the Kenya Motor Sports Federation calendar. It is also a social occasion and a fun-filled family day.",
             featuring: "Cool Classic Cars",
             dress_code: "Casual",
             location: "Karen",
             date: Date.new(2023, 8, 15),
             time: Time.new(2023, 8, 15, 12, 0, 0),
             tickets: 200,
             price: 20
           
},
{
    title: "Lovers Rock",
    image: "https://tikiti.co.ke/images/641dac37ba07a.jpg",
    category: "Music",
    description: "Lover's Rock is thrilled to announce Gyptian as the headlining artist for this year's event. Gyptian is a multi-award-winning reggae singer whose soulful voice and catchy beats have captivated audiences around the world. He has collaborated with some of the biggest names in the industry, including Nicki Minaj, Beenie Man, and Shaggy.",
    hosted_by: "Gyptian",
    featuring: "Nicki Minaj, Beenie Man, and Shaggy",
    dress_code: "Casual",
    location: "KICC",
    date: Date.new(2023, 6, 15),
    time: Time.new(2023, 6, 15, 19, 0, 0),
    tickets: 100,
    price: 10
},
{
    title: "I will marry when I want/Ngaahika Ndeenda",
        image: "https://tikiti.co.ke/images/63465765ec54b.jpg",
        category: "Theatre plays",
        description: "FOLLOWING ITS SOLD-OUT RUN IN MAY NGUGI WA THIONG’O/NGUGI WA MIRII’s iconic play I’LL MARRY WHEN I WANT/NGAAHIKA NDEENDA is BACK BY PUBLIC DEMAND FOR ONE LAST TIME!
                      THIS IS YOUR LAST CHANCE to see this spectacular production before it is gone forever!.",
        hosted_by: "Stuari Nash",
        featuring: "Various actors",
        dress_code: "Smart casual",
        location: "Kenya National Theatre",
        date: Date.new(2023, 7, 1),
        time: Time.new(2023, 7, 1, 18, 0, 0),
        tickets: 200,
        price: 20
},
{
    title: "Bikers Family Fest 8",
    image: "https://tikiti.co.ke/images/6275fa9d19270.jpg",
    category: "Sports",
    description: "Family Fest 8 is a one day event aimed at bringing families together. 
    It is tailored so that there is something for anyone. 
    The Biker's Edition will showcasing the best of bikers in Kenya as we unite around peace and unity as a nation and as families.",
    hosted_by: "Mc Gogo",
    featuring: "Kenya Bikers Association",
    dress_code: "Casual",
    location: "The Waterfront, Karen",
    date: Date.new(2023, 8, 15),
    time: Time.new(2023, 8, 15, 12, 0, 0),
    tickets: 300,
    price: 20
},
{
    title: "The Magharibi Festival",
             image: "https://tikiti.co.ke/images/6389d2722bf13.jpg",
             category: "Culture",
             description: "Magharibi Festival is a premier annual event of Western Kenya that sets out to celebrate the cultural diversity, talents, and beauty of Western Kenya.",
             hosted_by: "Steve Kay",
             featuring: "Harry Richie,Marry Richie",
             dress_code: "Casual",
             location: "Tourist Hotel, Bungoma",
             date: Date.new(2023, 8, 15),
             time: Time.new(2023, 8, 15, 12, 0, 0),
             tickets: 400,
             price: 20
},
{
    title: "Nairobi Sunset GT",
             image: "https://portal.mtickets.net/storage/display_images/7sZfYaZ8Rsiu15SLbXGp4YomHKkTKo1guNkyI8rb.jpeg",
             category: "Motor Show",
             description: "Sunset Gt motor show is an event that showcases a wide variety of automobiles, ranging from classic cars to the latest models of sports cars, luxury cars, electric vehicles, and other cutting-edge automotive technologies. The purpose of the event is to provide car enthusiasts, industry professionals, and the general public with a unique opportunity to see the latest trends and innovations in the automotive industry.",
             hosted_by: "Daimler Motorsports Kenya",
             featuring: "Tuned and modded cars",
             dress_code: "Casual",
             location: "Two Rivers Mall",
             date: Date.new(2023, 8, 15),
             time: Time.new(2023, 8, 15, 12, 0, 0),
             tickets: 200,
             price: 20
},
{
    title: "Reggae Music Extravaganza",
    image: "https://tikiti.co.ke/images/63ac11963d8c2.jpg",
    category: "Music",
    description: "Mombasa Nyali Community Ambassadors MNCAS  CBO Kenya welcomes you to their Mental Health Prevention New Year Music Entertainment Extravaganza Event 2023.",
    hosted_by: "Jane Chege",
    featuring: "Dj Queen of the mountain, MC Power",
    dress_code: "Jamaican Flag",
    location: "Mombasa, Nyali Beach",
    date: Date.new(2023, 6, 15),
    time: Time.new(2023, 6, 15, 19, 0, 0),
    tickets: 100,
    price: 10
},
{
    title: "It Wasnt Me",
    image: "https://www.ticketsasa.com/components/com_enmasse/upload/It_Wasnt_me.jpeg1681204112.jpg",
    category: "Theatre plays",
    description: "It wasn't me is a contemporary play about a contemporary couple that has found itself in a not so contemporary situation.
                  Alan, a writer, in a bid to get a story for his new play after his previous production bombed, pretends to have killed his best friend Patrick. Eve, his wife, after being told thus, involuntarily admits to have cheated on Alan with Patrick.",
    hosted_by: "Beril Oondo",
    featuring: "Michelle Tayars, Derrick Omondi",
    dress_code: "Casual",
    location: "The Waterfront Mall",
    date: Date.new(2023, 11, 15),
    time: Time.new(2023, 11, 15, 20, 0, 0),
    tickets: 100,
    price: 10
},
{
    title: "Nairobi Bar Show",
    image: "https://tikiti.co.ke/images/63176f1b2831e.jpg",
    category: "Culture",
    description: "The Nairobi Bar Show is East Africa's Premier Showcase of beverage culture.
                 If you like your drinks and want to see the best in the business all in one place, showing off their finesse, the Bar Show is the place to be for you.",
    hosted_by: "Jameson",
    featuring: "The Cocktail Bar Nairobi",
    dress_code: "Black or White",
    location: "Ngong Racecourse",
    date: Date.new(2023, 8, 17),
    time: Time.new(2023, 8, 17, 16, 0, 0),
    tickets: 100,
    price: 10
},
{
    title: "The 2023 Magical Kenya Open",
    image: "https://tikiti.co.ke/images/6261cfb7ef4af.jpg",
    category: "Sports",
    description: "The 2022 Magical Kenya Open happening between 3 July to 6 July, 2023, will take place at the Muthaiga Golf Club. The European Tour, now known as the DP World Tour, will visit the historic Muthaiga Golf Club for the first time when the Magical Kenya Open returns to the Race to Dubai from March 3-6, 2022.",
    hosted_by: "Absa",
    featuring: "Proffessional boxers",
    dress_code: "Casual",
    location: "Karen golf course",
    date: Date.new(2023, 7, 3),

    time: Time.new(2023, 7, 3, 9, 0, 0),

    tickets: 100,
    price: 10
},
{
    title: "Masinga TT",
    image: "https://de.cdn-website.com/a4f8945f46504fdb8395fd73c3dc0ce0/DESKTOP/jpg/987.jpg",
    category: "Motor show",
    description: "The Masinga TT is an annual car event organized by club TT involving three main activities namely; Drags, Drifts and Gymkhana. Previously, the event featured hill climbs. Club TT hosts various events in different parts of the country including Kiambu, Muranga, Nyahururu and Masinga.",
    hosted_by: "Motor TT Club",
    featuring: "Best Drivers around the country",
    dress_code: "Casual",
    location: "Nyahururu airstrip",
    date: Date.new(2023, 10, 20),
    time: Time.new(2023, 10, 20, 19, 0, 0),
    tickets: 100,
    price: 10
},
{
    title: "Love is Blind Mixer",
    image: "https://tikiti.co.ke/images/6261cbef54fe2.jpg",
    category: "Music",
    description: "At the Argenti Sky Lounge & restaurant from 2pm to 9pm!
                  Do not miss out!
                  Get ready for a night of groovy beats, positive vibes and good times. Our event is a celebration of the rich cultural heritage and music of Jamaica, and we aim to transport you to the sunny shores of the Caribbean.
                 As you walk in, you'll be greeted with a colorful atmosphere, complete with vibrant decorations, reggae-inspired art, and flags representing the Caribbean. The stage will be set with an array of musical instruments, and our talented musicians will be ready to deliver an unforgettable performance.
                The music will be a mix of traditional and contemporary reggae, featuring popular classics and new releases from the genre. The rhythm section will provide the backbone of the music, with pulsating bass lines and upbeat drum grooves that will get you moving. The horns will add a touch of soulful melody, while the vocals will be a reflection of the positive, uplifting lyrics that reggae is known for.",
    hosted_by: "Brian Msafiri",
    featuring: "Dj Paps",
    dress_code: "Casual",
    location: "Argenti Sky Lounge",
    date: Date.new(2023, 6, 15),
    time: Time.new(2023, 6, 15, 21, 0, 0),
    tickets: 100,
    price: 10
},
{
    title: "Stranger in my bed",
    image: "https://kenyaculturalcentre.go.ke/portal/api/docs/1516169475A%20STRANGER%20IN%20MY%20BED.jpeg",
    category: "Theatre plays",
    description: "This is a one woman play of duration 90minutes fusing dance and storytelling enactment. The story talks about the life of a young girl, a performing artist, who gets into a long distance love and then a long distance marriage at the age of 25yrs to a military man.",
    hosted_by: "Zippy Okoth",
    featuring: "Zippy Okoth",
    dress_code: "Casual",
    location: "Kenya National Theatre",
    date: Date.new(2024, 6, 14),
    time: Time.new(2024, 6, 14, 18, 0, 0),
    tickets: 100,
    price: 10
},
{
    title: "The Culture",
    image: "https://tikiti.co.ke/images/638a274f97d9a.jpg",
    category: "Culture",
    description: "Get Ready to Celebrate our Culture through Music and Dance 
                 On the 10th of December 2022 at the Winning Post, Ngong Race Course.",
    hosted_by: "Josiah De Disciple",
    featuring: "Brandy Maina",
    dress_code: "Casual",
    location: "The Winning Spot",
    date: Date.new(2023, 12, 12),
    time: Time.new(2023, 12, 12, 21, 0, 0),
    tickets: 100,
    price: 10
},
{
    title: "Enterprise Cup Finals",
    image: "https://storage.googleapis.com/m_tickets/assets/event_poster/enterprise-cup-final2023-04-13T18-48-39.968742.jpeg",
    category: "Sports",
    description: "ECF  event is a gathering of programmers and enthusiasts who are passionate about the Ruby programming language. This event is an opportunity for Ruby developers to come together to share their knowledge and experience, learn new things, and network with other like-minded individuals.",
    hosted_by: "Rubby Union",
    featuring: "Kabras Sugar and KCB",
    dress_code: "Casual",
    location: "RFUEA Grounds",
    date: Date.new(2023, 4, 15),
    time: Time.new(2023, 4, 15, 11, 0, 0),
    tickets: 100,
    price: 10
},
{
    title: "Drag Rivals",
    image: "https://jamaicamotorsports.com/wp-content/uploads/2019/03/DRAG-RIVALS-2-2019-sanctioned.png",
    category: "Motorshow",
    description: "The fourth round of the WSK Super Master Series, held at International Circuit Napoli in Sarno, Italy on March 24th certainly didn’t go the way Alex Powell might have planned but in the end his series consistency paid off for 3rd in the WSK Super Master Series Championship.",
    hosted_by: "Jam West",
    featuring: "Racers from around the country",
    dress_code: "Casual",
    location: "Little London",
    date: Date.new(2023, 6, 15),
    time: Time.new(2023, 6, 15, 19, 0, 0),
    tickets: 100,
    price: 10
},
{
    title: "Tukutane Festival",
    image: "https://tikiti.co.ke/images/63234c9656cf5.jpg",
    category: "Music",
    description: "Fans can expect to hear some of her most popular songs, such as Mr Rebel, These Days, and Damages. Tems' performances are known for their high energy and captivating stage presence, with her soulful voice and unique style captivating audiences.",
    hosted_by: "Tukutane",
    featuring: "Tems",
    dress_code: "Casual",
    location: "Waterfront Mall",
    date: Date.new(2023, 6, 15),
    time: Time.new(2023, 6, 15, 19, 0, 0),
    tickets: 100,
    price: 10,
},
{
    title: "Dead Talk",
    image: "https://kenyaculturalcentre.go.ke/portal/api/docs/1517920728Dead%20Talk.jpeg",
    category: "Theatre play",
    description: "The whispered conversations of ghosts in a city morgue are not just a result of Pacos fertile imagination nor Noahs drunken stupor.",
    hosted_by: "Cajetan Boy",
    featuring: "Various actors",
    dress_code: "Smart casual",
    location: "Kenya National Theatre",
    date: Date.new(2023, 7, 1),
    time: Time.new(2023, 7, 1, 18, 0, 0),
    tickets: 50,
    price: 0,
},
{
    title: "The Mo Festival",
    image: "https://www.ticketsasa.com/components/com_enmasse/upload/WhatsApp_Image_2023-03-31_at_11.01.24.jpeg1680253037.jpg",
    category: "Culture",
    description: "The Mo Festival - featuring some of the BEST music artists that Kenya has to offer taking place at the KICC on Sat 29th April 2023.   The event is fully sponsored by The Mo Ibrahim Foundation and is anchored by the goal of championing Africa's youth participation in the continent's development.",
    hosted_by: "Nyashinski",
    featuring: "Femi One,Otile Brown,Dj Joe Mfalme,Otile Brown",
    dress_code: "Casual",
    location: "KICC",
    date: Date.new(2023, 4, 29),
    time: Time.new(2023, 4, 29, 12, 0, 0),
    tickets: 200,
    price: 20,
},
{
    title: "World Under 20 Championships",
    image: "https://d1csarkz8obe9u.cloudfront.net/posterpreviews/world-athletics-day-instagram-post-design-template-97d146133d2eaf6f04870e6813ce794a_screen.jpg?ts=1620140651",
    category: "Sports",
    description: "As the athletes arrive at the event, they are filled with excitement and anticipation for the upcoming competitions. The atmosphere is electric, with music blaring from the speakers, colorful flags waving in the breeze, and the sound of enthusiastic fans echoing through the stadium.",
    hosted_by: "Kanary Sports ",
    featuring: "Local Athletes",
    dress_code: "Casual",
    location: "Draja sports grounds",
    date: Date.new(2023, 6, 15),
    time: Time.new(2023, 6, 15, 19, 0, 0),
    tickets: 100,
    price: 10,
},
{
    title: "Tuner Motor Show",
    image: "https://storage.googleapis.com/m_tickets/assets/event_poster/TunerFestival2023-02-16T17-22-272023-02-20T13-13-21.597937.jpg",
    category: "Motorshow",
    description: "This year's event promises to be bigger and better than ever, showcasing hundreds of sports cars, classic & vintage cars, exotic cars, Japanese Legends, German perfomance, the fastest superbikes around to beastly offroaders - there is something for everyone.",
    hosted_by: "Al-Husein Motors",
    featuring: "Tuned Rides",
    dress_code: "Smart casual",
    location: "Westgate Shopping Mall",
    date: Date.new(2023, 7, 1),
    time: Time.new(2023, 7, 1, 18, 0, 0),
    tickets: 50,
    price: 10,
},
{
    title: "Soul White Party",
    image: "https://tikiti.co.ke/images/63ab0b89502b2.jpg",
    category: "Music",
    description: "Soul En Blanc
                  Soul White Party
                  Carnivore Simba Saloon
                  Our event is a celebration of this timeless genre, and we aim to bring you an unforgettable experience that will leave you wanting more.
                  As you enter, you'll be greeted with a warm and inviting atmosphere, complete with dimmed lights, plush seating, and an elegant stage set with musical instruments. Our talented musicians will be ready to deliver a powerful performance that will showcase the beauty and depth of soul music.",
    hosted_by: "Dj Adrian",
    featuring: "Dj John, Dj E, Dj Wattson",
    dress_code: "White",
    location: "Carnivore Simba Saloon",
    date: Date.new(2023, 8, 15),
    time: Time.new(2023, 8, 15, 12, 0, 0),
    tickets: 200,
    price: 20,
},
{
    title: "The Taitanic",
    image: "https://www.subplotstudio.com/resources/images/productions/4327/9409/art.sample.437.jpg",
    category: "Theatre play",
    description: "The eponymous character, Edufa, is a western educated man, wealthy and well respected by the society who has an obsessive desire to live long. To satisfy this unquenchable thirst, he consults a diviner who tells him to find someone who loves him and is willing to die for him.",
    hosted_by: "The Clan",
    featuring: "Karen Odongo",
    dress_code: "Casual",
    location: "Central Park",
    date: Date.new(2023, 6, 20),
    time: Time.new(2023, 6, 20, 19, 0, 0),
    tickets: 100,
    price: 10,
},
{
    title: "The Sunday Braai",
    image: "https://www.ticketsasa.com/components/com_enmasse/upload/IMG_0346.JPG1681368087.jpg",
    category: "Culture",
    description: "Sample dishes from some of the city's top chefs.The event can include performances, exhibitions, workshops, and interactive activities that highlight the unique aspects of the culture being celebrated. Food and drinks can also be an important part of the event, allowing attendees to sample traditional dishes and learn about the culinary traditions of the culture being celebrated.",
    hosted_by: "Equipe Choque",
    featuring: "Local chefs",
    dress_code: "Casual",
    location: "African",
    date: Date.new(2023, 8, 15),
    time: Time.new(2023, 8, 15, 12, 0, 0),
    tickets: 200,
    price: 20,
},
{
    title: "Copa Del Nairobi",
    image: "https://d1csarkz8obe9u.cloudfront.net/posterpreviews/soccer-tournament-poster-template-instagram-design-0c0ab6c532dbcf9cd1ede0caf0cd78c9_screen.jpg?ts=1624461367",
    category: "Sports",
    description: "Copa Del is a football tournament showcasing local talent and offering potentials a chance to make it to the big leagues.",
    hosted_by: "Copa Del",
    featuring: "Local Football Talent",
    dress_code: "Casual",
    location: "The Void Turf",
    date: Date.new(2023, 6, 15),
    time: Time.new(2023, 6, 15, 19, 0, 0),
    tickets: 100,
    price: 10,
},
{
    title: "Athi Time Attack",
    image: "https://portal.mtickets.net/storage/display_images/ZmzVLBdc8UIUv9HbHoaHgOiBwr0XMGiNtJASkLFO.jpeg",
    category: "Motorshow",
    description: "Come see the best of the best hit the track with in fastest time laps.Everything  from tuned rides to professional drivers.",
    hosted_by: "The Motorsport",
    featuring: "Local Racers",
    dress_code: "Casual",
    location: "Whistlin Morans Attack",
    date: Date.new(2023, 8, 15),
    time: Time.new(2023, 8, 15, 12, 0, 0),
    tickets: 200,
    price: 20,
},
{
    title: "Sol Fest",
    image: "https://tikiti.co.ke/images/6261cf0ba03fe.jpg",
    category: "Music",
    description: "Sol Fest by Sol Generation and Homeboyz Entertainment Sauti Sol x Bensoul x Nviiri The Storyteller and many more Sol Generations inaugural Festival curated to showcase Kenyas best talent.",
    hosted_by: "Homeboyz Radio",
    featuring: "Sol Generation",
    dress_code: "Casual",
    location: "KICC",
    date: Date.new(2023, 6, 15),
    time: Time.new(2023, 6, 15, 19, 0, 0),
    tickets: 100,
    price: 10,
},
{
    title: "The Silent Apocalypse",
    image: "https://kenyaculturalcentre.go.ke/portal/api/docs/1540387232IMG-20181023-WA0014.jpg",
    category: "Theatre play",
    description: "A thrilling ride through a mystic story line.",
    hosted_by: "KNT Ukumbi ndogo",
    featuring: "Stephanie",
    dress_code: "Casual",
    location: "Kenya National Theatre",
    date: Date.new(2023, 6, 15),
    time: Time.new(2023, 6, 15, 19, 0, 0),
    tickets: 100,
    price: 10,
},
{
    title: "Club Kiboko Festival",
    image: "https://www.ticketsasa.com/components/com_enmasse/upload/Club_Kiboko_Fun_Day_1000_by_1000.jpg1679645400.jpg",
    category: "Culture",
    description: "Join us for a day of fu activities for kids including;play ground,face painting and parents activities too.Dont miss out!.",
    hosted_by: "Standard Group",
    featuring: "Fun activites",
    dress_code: "Casual",
    location: "Ulinzi Sports Complex",
    date: Date.new(2023, 6, 15),
    time: Time.new(2023, 6, 15, 19, 0, 0),
    tickets: 100,
    price: 10,
},
{
    title: "Skills Gala",
    image: "https://swimafrica.net/wp-content/uploads/2022/04/SKILLS-JUNE-2022.jpeg",
    category: "Sports",
    description: "Its Back! Its exciting! Weve been training for 2 years, its time to showcase! The only event of its kind! Complete with medals and trophies.Let your swimmers shine!.",
    hosted_by: "Skills Gala",
    featuring: "Junior Swimmers",
    dress_code: "Casual",
    location: "Montessori Learning Center",
    date: Date.new(2023, 8, 15),
    time: Time.new(2023, 8, 15, 12, 0, 0),
    tickets: 200,
    price: 20,
},
{
    title: "Events Cars",
    image: "https://eventswithcars.com/wp-content/uploads/2022/05/Edina-Car-Show-2022.jpg",
    category: "Motorshow",
    description: "Fellow Car Enthusiasts! Please join us for the Fourth Annual Edina Car Show on Saturday, Septemeber 10, 2022 from 12-4pm. This is a family-friendly event, and awards will be given out for Best in Show (Owners & Peoples Choice), and Top 5 Cars! We are excited to have Northstar Cadillac Lasalle Club and Great Northern Region  Lambda Car Club International as our volunteer-sponsors.",
    hosted_by: "Rotery club of Adina",
    featuring: "Local Car Enthusiasts",
    dress_code: "Casual",
    location: "SouthDale Center Parking Lot",
    date: Date.new(2023, 8, 15),
    time: Time.new(2023, 8, 15, 12, 0, 0),
    tickets: 200,
    price: 20,
},
{
    title: "LOUD 420 Edition",
    image: "https://storage.googleapis.com/m_tickets/assets/event_poster/loud-420-edition-2023-04-13T15-47-26.473199.jpeg",
    category: "Music",
    description: "Club Performances Act that embraces , showcases and promotes the current trends I.E 420 and Kenyan Music Culture specifically focusing of all Upcoming Underground Artistes.",
    hosted_by: "Shirley",
    featuring: "Various artists",
    dress_code: "Smart casual",
    location: "Woodvale Groove,Westlands",
    date: Date.new(2023, 7, 1),
    time: Time.new(2023, 7, 1, 18, 0, 0),
    tickets: 50,
    price: 0,
},
{
    title: "Art of June",
    image: "https://kenyaculturalcentre.go.ke/portal/api/docs/1485337585All%20of%20June%20Poster.jpg",
    category: "Theatre play",
    description: "ALL OF JUNE a musical experience that promises to reveal sides of June Gachui that her audiences havent interacted with before.It will marry aspects of her work in theatre, comedy and dance as she, along with her fans and supporters continue to celebrate the twenty years that this iconic woman has spent on stage.",
    hosted_by: "Classic 105",
    featuring: "June Gachui",
    dress_code: "Smart casual",
    location: "The Kenya National Theatre",
    date: Date.new(2023, 7, 1),
    time: Time.new(2023, 7, 1, 18, 0, 0),
    tickets: 50,
    price: 0,
},
{
    title: "LUO FESTIVAL NAIROBI EDITION 2023",
    image: "https://storage.googleapis.com/m_tickets/assets/event_poster/luo_fest.jpg",
    category: "Culture",
    description: "The Luo Festival is a one-day cultural event that seeks to celebrate the  Luo culture and lifestyle. A culture of class, trendsetters, pacesetters, and the Learned..",
    hosted_by: "Arena media",
    featuring: "Mc Japolo,Mc Onyulo",
    dress_code: "Smart casual",
    location: "Nairobi",
    date: Date.new(2023, 7, 1),
    time: Time.new(2023, 7, 1, 18, 0, 0),
    tickets: 50,
    price: 0,
},
{
    title: "African Cup For Club Champions",
    image: "https://cdn.dribbble.com/users/617471/screenshots/5605171/media/7ecd76e2c335c4c0526b02c8b7ccc2d7.jpg?compress=1&resize=768x576&vertical=top",
    category: "Sports",
    description: "Come see your favourite hockey players in actoin.Throughout the match, players will utilize various techniques such as dribbling, passing, and shooting to try and score goals. The team that scores the most goals by the end of the match is declared the winner. In the event of a tie, the match may go into extra time or a penalty shootout to determine the winner.

    Football events are often accompanied by enthusiastic crowds, cheering on their favorite teams and players. The atmosphere is electric, with excitement building as the match progresses and the score remains close. Overall, football events provide an exciting and thrilling experience for players and fans alike.",
    hosted_by: "KCCC",
    featuring: "Various hockey Teams",
    dress_code: "Smart casual",
    location: "Nairobi",
    date: Date.new(2023, 7, 1),
    time: Time.new(2023, 7, 1, 18, 0, 0),
    tickets: 50,
    price: 0,
},
{
    title: "Kenya Auto & Motor Show",
    image: "http://www.impact.co.th/userfiles/images/press/2022/02-11-43rd-motorshow2022-L.jpg",
    category: "Motorshow",
    description: "Int'l Trade Expo on al kind of Auto, Auto Parts, Accessories, Aftermarket, Feeding Industries, Retailing, Vehicle Parts, Chemicals Equipments, Auto Products, Hybrid Motor's & machinery etc.",
    hosted_by: "Auto & Motor",
    featuring: "Various Rides",
    dress_code: "Smart casual",
    location: "KICC",
    date: Date.new(2023, 7, 1),
    time: Time.new(2023, 7, 1, 18, 0, 0),
    tickets: 50,
    price: 0,
},
{
    title: "Choma Fest",
    image: "https://storage.googleapis.com/m_tickets/assets/event_poster/C4A1FFE2-1A1B-4905-A740-AA09E77B2D652023-03-20T14-15-55.711908.jpeg",
    category: "Music",
    description: "choma is funbase where every young talents gets platforms to showcase their talents and giving various people opportunity to sample their meat choma with a vibe of music.",
    hosted_by: "Kisumu Come Out Investment",
    featuring: "Bruklyn Boyz",
    dress_code: "Casual",
    location: "Showground Mamboleo",
    date: Date.new(2023, 6, 15),
    time: Time.new(2023, 6, 15, 19, 0, 0),
    tickets: 100,
    price: 10,
},
{
    title: "The Audacity of Hope",
    image: "https://www.ticketsasa.com/components/com_enmasse/upload/PHOTO-2023-04-14-11-36-05.jpg1681463904.jpg",
    category: "Theatre play",
    description: "Where would we be without hope? Hope in the face of difficulty,  Hope in the face of uncertainty. Hope against all odds. Ultimately, Gods greatest gift to us is hope.",
    hosted_by: "Engage Kenya Limited",
    featuring: "Local talent",
    dress_code: "Casual",
    location: "Kenya National Theatre",
    date: Date.new(2023, 6, 15),
    time: Time.new(2023, 6, 15, 19, 0, 0),
    tickets: 100,
    price: 10,
},
{
    title: "Affordable Art Show",
    image: "https://www.ticketsasa.com/components/com_enmasse/upload/Final_12-14_May_2023_AAS_Poster.jpg1680683701.jpg",
    category: "Culture",
    description: " Art exhibition and sale.",
    hosted_by: "Kenya Museum Society",
    featuring: "Art",
    dress_code: "Casual",
    location: "National Museum",
    date: Date.new(2023, 6, 15),
    time: Time.new(2023, 6, 15, 19, 0, 0),
    tickets: 100,
    price: 10,
},
{
    title: "Gun Shooting Day Trip",
    image: "https://cdn2.allevents.in/thumbs/thumb6422c60360d5b.jpg",
    category: "Sports",
    description: "Xtreme Republic is presenting the second edition to Kwenia Ammodump for Gun shooting.",
    hosted_by: "Xtremerepublic",
    featuring: "Free for all",
    dress_code: "Casual",
    location: "Herik",
    date: Date.new(2023, 6, 15),
    time: Time.new(2023, 6, 15, 19, 0, 0),
    tickets: 100,
    price: 10,
},
{
    title: "The Madretude",
    image: "https://www.kenyabuzz.com/public//uploads/posters/1652255138.jpg",
    category: "Motorshow",
    description: "Singapores largest and most iconic annual motoring event, the Singapore Motorshow will mark its return after a three-year hiatus at Suntec Singapore Convention & Exhibition Centre from January 12 to 15 2023.",
    hosted_by: "Motul",
    featuring: "Local Tuners",
    dress_code: "Casual",
    location: "Singapore",
    date: Date.new(2023, 6, 15),
    time: Time.new(2023, 6, 15, 19, 0, 0),
    tickets: 100,
    price: 10,
},
{
    title: "Royal Orange Disco",
    image: "https://www.ticketsasa.com/components/com_enmasse/upload/19CBAF88-4A03-4451-A625-4B818E823DA5.jpeg1680330595.jpg",
    category: "Music",
    description: "Koningsdag is a national holiday in the Kingdom of the Netherlands. Celebrated on 27 April the date marks the birth of King Willem-Alexander.",
    hosted_by: "Het Koningsdag Feest Committee",
    featuring: "Various artists",
    dress_code: "casual black",
    location: "Matteo's Karen",
    date: Date.new(2023, 7, 2),
    time: Time.new(2023, 7, 2, 18, 0, 0),
    tickets: 50,
    price: 0,
},
{
    title: "Music Concert",
    image: "https://kenyaculturalcentre.go.ke/portal/api/docs/1523546267MUSIC%20CONCERT.jpg",
    category: "Theatre play",
    description: "Come see the latest works of local artists at work LIVE!.",
    hosted_by: "The Gallery",
    featuring: "Various artists",
    dress_code: "Smart casual",
    location: "Kenya National Theatre",
    date: Date.new(2023, 7, 3),
    time: Time.new(2023, 7, 3, 18, 0, 0),
    tickets: 50,
    price: 0,
},
{
    title: "A Night in Las Vagas Nairobi",
    image: "https://storage.googleapis.com/m_tickets/assets/event_poster/karnival.png",
    category: "Culture",
    description: "Come sample the best  of the best in local culture from music to food to local music from traditional instruments.",
    hosted_by: "Trip in the Wild",
    featuring: "Various artists",
    dress_code: "Smart casual",
    location: "Space X Karen",
    date: Date.new(2023, 5, 1),
    time: Time.new(2023, 5, 1, 18, 0, 0),
    tickets: 50,
    price: 0,
},
{
    title: "Smart sports",
    image: "https://sportsgroundproduction.blob.core.windows.net/cms/8789/61436/1426392/b49e36e9-11e9-4b22-85b3-fc8c850785b7_wo.png?t=638170817411300000",
    category: "Sports",
    description: "The final show who will take it all.Throughout the match, players will utilize various techniques such as dribbling, passing, and shooting to try and score goals. The team that scores the most goals by the end of the match is declared the winner. In the event of a tie, the match may go into extra time or a penalty shootout to determine the winner.
                 Football events are often accompanied by enthusiastic crowds, cheering on their favorite teams and players. The atmosphere is electric, with excitement building as the match progresses and the score remains close. Overall, football events provide an exciting and thrilling experience for players and fans alike.",
    hosted_by: "Sportpesa",
    featuring: "Various local football clubs",
    dress_code: "Smart casual",
    location: "Kasarani sports center",
    date: Date.new(2023, 8, 7),
    time: Time.new(2023, 8, 7, 18, 0, 0),
    tickets: 50,
    price: 0,
},
{
    title: "Central Africa Motorcross Challange",
    image: "https://www.kenyabuzz.com/public//uploads/posters/1657097450.jpeg",
    category: "Motorshow",
    description: "Come see the latest works of local pro dirt bike racers.car drift show is a thrilling and exciting event that showcases the skill and precision of drivers as they navigate their cars through a series of turns and twists with incredible speed and control. The show takes place on a specially designed track, which may include obstacles and sharp turns to challenge the drivers and add to the excitement.
                  Drifting is a driving technique where the driver intentionally oversteers the car, causing the rear wheels to lose traction and slide sideways. Skilled drivers use this technique to maintain control of their vehicles while maneuvering through tight turns and corners at high speeds.",
    hosted_by: "FIM",
    featuring: "Various artists",
    dress_code: "casual",
    location: "Athi River",
    date: Date.new(2023, 11, 13),
    time: Time.new(2023, 11, 13, 20, 0, 0),
    tickets: 50,
    price: 0,
},
])
puts "✅ Done seeding!"
